version: '3'
services:
  elastic_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0-beta1
    environment:
     - http.cors.enabled=true
     - http.port=9200
     - http.cors.allow-origin="*"
     - cluster.name=es_newprolab
     - network.host=_site_
     - discovery.type=single-node
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
     - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
     